site_name: District ZER0
repo_url: https://github.com/SBD1/2025.1-District-ZER0/
repo_name: District ZER0

theme:
  name: material
  language: pt-BR
  logo: assets/favicon.png
  favicon: assets/favicon.png
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight

# CSS personalizado
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.emoji
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.details

nav:
  - Início: index.md
  - Módulo 1:
    - Dicionário de Dados: modulo1/DD.md
    - Modelo Entidade Relacionamento: modulo1/MER.md
    - Diagrama Entidade Relacionamento: modulo1/DER.md
    - Modelo Relacional: modulo1/MREL.md
    - Apresentação do Módulo: modulo1/apresentacao.md

  - Módulo 2:
    - Guia de Setup com Docker: modulo2/setup-docker.md
    - Implementação SQL: modulo2/implementacao-sql.md
    - Infraestrutura Docker: modulo2/infraestrutura-docker.md
    - Apresentação do Módulo: modulo2/apresentacao.md

  - Guia de Contribuição:
    - guia-de-contribuicao/politica-de-branches.md
    - guia-de-contribuicao/politica-de-commits.md

plugins:
  - search 